################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal.c \
C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_cortex.c \
C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma.c \
C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma_ex.c \
C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_exti.c \
C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_gpio.c \
C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr.c \
C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr_ex.c \
C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc.c \
C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc_ex.c \
C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rif.c \
C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart.c \
C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart_ex.c 

OBJS += \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal.o \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_cortex.o \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma.o \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma_ex.o \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_exti.o \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_gpio.o \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr.o \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr_ex.o \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc.o \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc_ex.o \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rif.o \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart.o \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart_ex.o 

C_DEPS += \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal.d \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_cortex.d \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma.d \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma_ex.d \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_exti.d \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_gpio.d \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr.d \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr_ex.d \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc.d \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc_ex.d \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rif.d \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart.d \
./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart_ex.d 


# Each subdirectory must supply rules for building sources it contributes
STM32N6xx_HAL_Driver/Src/stm32n6xx_hal.o: C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal.c STM32N6xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/IMX335" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/isp_param_conf" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/ToF" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Core/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/VL53L7CX_ULD/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_cortex.o: C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_cortex.c STM32N6xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/IMX335" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/isp_param_conf" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/ToF" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Core/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/VL53L7CX_ULD/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma.o: C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma.c STM32N6xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/IMX335" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/isp_param_conf" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/ToF" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Core/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/VL53L7CX_ULD/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma_ex.o: C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma_ex.c STM32N6xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/IMX335" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/isp_param_conf" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/ToF" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Core/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/VL53L7CX_ULD/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_exti.o: C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_exti.c STM32N6xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/IMX335" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/isp_param_conf" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/ToF" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Core/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/VL53L7CX_ULD/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_gpio.o: C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_gpio.c STM32N6xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/IMX335" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/isp_param_conf" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/ToF" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Core/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/VL53L7CX_ULD/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr.o: C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr.c STM32N6xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/IMX335" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/isp_param_conf" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/ToF" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Core/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/VL53L7CX_ULD/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr_ex.o: C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr_ex.c STM32N6xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/IMX335" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/isp_param_conf" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/ToF" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Core/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/VL53L7CX_ULD/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc.o: C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc.c STM32N6xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/IMX335" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/isp_param_conf" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/ToF" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Core/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/VL53L7CX_ULD/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc_ex.o: C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc_ex.c STM32N6xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/IMX335" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/isp_param_conf" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/ToF" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Core/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/VL53L7CX_ULD/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rif.o: C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rif.c STM32N6xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/IMX335" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/isp_param_conf" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/ToF" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Core/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/VL53L7CX_ULD/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart.o: C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart.c STM32N6xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/IMX335" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/isp_param_conf" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/ToF" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Core/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/VL53L7CX_ULD/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart_ex.o: C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart_ex.c STM32N6xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N657xx -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/IMX335" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/Camera/isp_param_conf" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/ToF" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Core/Inc" -I"C:/Users/Thepr/STM32Projects/Blindsight-Claritone-Senior-Design/Firmware/Claritone_L5_Camera/Appli/Drivers/VL53L7CX_ULD/Inc" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-STM32N6xx_HAL_Driver-2f-Src

clean-STM32N6xx_HAL_Driver-2f-Src:
	-$(RM) ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal.cyclo ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal.d ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal.o ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal.su ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_cortex.cyclo ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_cortex.d ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_cortex.o ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_cortex.su ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma.cyclo ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma.d ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma.o ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma.su ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma_ex.cyclo ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma_ex.d ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma_ex.o ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma_ex.su ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_exti.cyclo ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_exti.d ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_exti.o ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_exti.su ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_gpio.cyclo ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_gpio.d ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_gpio.o ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_gpio.su ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr.cyclo ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr.d ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr.o ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr.su ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr_ex.cyclo ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr_ex.d ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr_ex.o ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr_ex.su ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc.cyclo ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc.d ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc.o ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc.su ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc_ex.cyclo ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc_ex.d ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc_ex.o ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc_ex.su ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rif.cyclo ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rif.d ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rif.o ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rif.su ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart.cyclo ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart.d ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart.o ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart.su ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart_ex.cyclo ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart_ex.d ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart_ex.o ./STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart_ex.su

.PHONY: clean-STM32N6xx_HAL_Driver-2f-Src

