################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/zebes/Blindsight_Projects/STM32Cube_FW_N6_V1.3.0/Middlewares/ST/STM32_ExtMem_Manager/boot/stm32_boot_xip.c \
C:/Users/zebes/Blindsight_Projects/STM32Cube_FW_N6_V1.3.0/Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.c \
C:/Users/zebes/Blindsight_Projects/STM32Cube_FW_N6_V1.3.0/Middlewares/ST/STM32_ExtMem_Manager/psram/stm32_psram_driver.c \
C:/Users/zebes/Blindsight_Projects/STM32Cube_FW_N6_V1.3.0/Middlewares/ST/STM32_ExtMem_Manager/sal/stm32_sal_xspi.c \
C:/Users/zebes/Blindsight_Projects/STM32Cube_FW_N6_V1.3.0/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_data.c \
C:/Users/zebes/Blindsight_Projects/STM32Cube_FW_N6_V1.3.0/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_driver.c 

OBJS += \
./Middlewares/STM32_ExtMem_Manager/stm32_boot_xip.o \
./Middlewares/STM32_ExtMem_Manager/stm32_extmem.o \
./Middlewares/STM32_ExtMem_Manager/stm32_psram_driver.o \
./Middlewares/STM32_ExtMem_Manager/stm32_sal_xspi.o \
./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_data.o \
./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_driver.o 

C_DEPS += \
./Middlewares/STM32_ExtMem_Manager/stm32_boot_xip.d \
./Middlewares/STM32_ExtMem_Manager/stm32_extmem.d \
./Middlewares/STM32_ExtMem_Manager/stm32_psram_driver.d \
./Middlewares/STM32_ExtMem_Manager/stm32_sal_xspi.d \
./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_data.d \
./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_driver.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/STM32_ExtMem_Manager/stm32_boot_xip.o: C:/Users/zebes/Blindsight_Projects/STM32Cube_FW_N6_V1.3.0/Middlewares/ST/STM32_ExtMem_Manager/boot/stm32_boot_xip.c Middlewares/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g -DDEBUG -DSTM32_EXTMEMLOADER_STM32CUBETARGET -DSTM32N657xx -c -I../../../Secure_nsclib -I../../../ExtMemLoader/Inc -I../../../../../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/core -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/MDK-ARM -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/STM32Cube -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../../../../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include/Templates -I../../../../../../../Drivers/CMSIS/Include -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ExtMem_Manager/stm32_extmem.o: C:/Users/zebes/Blindsight_Projects/STM32Cube_FW_N6_V1.3.0/Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.c Middlewares/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g -DDEBUG -DSTM32_EXTMEMLOADER_STM32CUBETARGET -DSTM32N657xx -c -I../../../Secure_nsclib -I../../../ExtMemLoader/Inc -I../../../../../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/core -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/MDK-ARM -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/STM32Cube -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../../../../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include/Templates -I../../../../../../../Drivers/CMSIS/Include -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ExtMem_Manager/stm32_psram_driver.o: C:/Users/zebes/Blindsight_Projects/STM32Cube_FW_N6_V1.3.0/Middlewares/ST/STM32_ExtMem_Manager/psram/stm32_psram_driver.c Middlewares/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g -DDEBUG -DSTM32_EXTMEMLOADER_STM32CUBETARGET -DSTM32N657xx -c -I../../../Secure_nsclib -I../../../ExtMemLoader/Inc -I../../../../../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/core -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/MDK-ARM -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/STM32Cube -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../../../../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include/Templates -I../../../../../../../Drivers/CMSIS/Include -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ExtMem_Manager/stm32_sal_xspi.o: C:/Users/zebes/Blindsight_Projects/STM32Cube_FW_N6_V1.3.0/Middlewares/ST/STM32_ExtMem_Manager/sal/stm32_sal_xspi.c Middlewares/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g -DDEBUG -DSTM32_EXTMEMLOADER_STM32CUBETARGET -DSTM32N657xx -c -I../../../Secure_nsclib -I../../../ExtMemLoader/Inc -I../../../../../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/core -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/MDK-ARM -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/STM32Cube -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../../../../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include/Templates -I../../../../../../../Drivers/CMSIS/Include -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ExtMem_Manager/stm32_sfdp_data.o: C:/Users/zebes/Blindsight_Projects/STM32Cube_FW_N6_V1.3.0/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_data.c Middlewares/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g -DDEBUG -DSTM32_EXTMEMLOADER_STM32CUBETARGET -DSTM32N657xx -c -I../../../Secure_nsclib -I../../../ExtMemLoader/Inc -I../../../../../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/core -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/MDK-ARM -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/STM32Cube -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../../../../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include/Templates -I../../../../../../../Drivers/CMSIS/Include -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_ExtMem_Manager/stm32_sfdp_driver.o: C:/Users/zebes/Blindsight_Projects/STM32Cube_FW_N6_V1.3.0/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_driver.c Middlewares/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g -DDEBUG -DSTM32_EXTMEMLOADER_STM32CUBETARGET -DSTM32N657xx -c -I../../../Secure_nsclib -I../../../ExtMemLoader/Inc -I../../../../../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/core -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/MDK-ARM -I../../../../../../../Middlewares/ST/STM32_ExtMem_Loader/STM32Cube -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../../../../../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../../../../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include/Templates -I../../../../../../../Drivers/CMSIS/Include -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-STM32_ExtMem_Manager

clean-Middlewares-2f-STM32_ExtMem_Manager:
	-$(RM) ./Middlewares/STM32_ExtMem_Manager/stm32_boot_xip.cyclo ./Middlewares/STM32_ExtMem_Manager/stm32_boot_xip.d ./Middlewares/STM32_ExtMem_Manager/stm32_boot_xip.o ./Middlewares/STM32_ExtMem_Manager/stm32_boot_xip.su ./Middlewares/STM32_ExtMem_Manager/stm32_extmem.cyclo ./Middlewares/STM32_ExtMem_Manager/stm32_extmem.d ./Middlewares/STM32_ExtMem_Manager/stm32_extmem.o ./Middlewares/STM32_ExtMem_Manager/stm32_extmem.su ./Middlewares/STM32_ExtMem_Manager/stm32_psram_driver.cyclo ./Middlewares/STM32_ExtMem_Manager/stm32_psram_driver.d ./Middlewares/STM32_ExtMem_Manager/stm32_psram_driver.o ./Middlewares/STM32_ExtMem_Manager/stm32_psram_driver.su ./Middlewares/STM32_ExtMem_Manager/stm32_sal_xspi.cyclo ./Middlewares/STM32_ExtMem_Manager/stm32_sal_xspi.d ./Middlewares/STM32_ExtMem_Manager/stm32_sal_xspi.o ./Middlewares/STM32_ExtMem_Manager/stm32_sal_xspi.su ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_data.cyclo ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_data.d ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_data.o ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_data.su ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_driver.cyclo ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_driver.d ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_driver.o ./Middlewares/STM32_ExtMem_Manager/stm32_sfdp_driver.su

.PHONY: clean-Middlewares-2f-STM32_ExtMem_Manager

