#ifndef CLARITONE_CUSTOM_BOARD_H
#define CLARITONE_CUSTOM_BOARD_H

#include "stm32n6xx_hal.h"
#include "cmw_camera.h"

#define CLARITONE_HEADLESS 1

#define CLARITONE_CONSOLE_UART                UART4
#define CLARITONE_CONSOLE_UART_CLK_ENABLE()   __HAL_RCC_UART4_CLK_ENABLE()
#define CLARITONE_CONSOLE_GPIO_CLK_ENABLE()   __HAL_RCC_GPIOA_CLK_ENABLE()
#define CLARITONE_CONSOLE_TX_PORT             GPIOA
#define CLARITONE_CONSOLE_TX_PIN              GPIO_PIN_0
#define CLARITONE_CONSOLE_TX_AF               GPIO_AF8_UART4
#define CLARITONE_CONSOLE_RX_PORT             GPIOA
#define CLARITONE_CONSOLE_RX_PIN              GPIO_PIN_1
#define CLARITONE_CONSOLE_RX_AF               GPIO_AF8_UART4

#define CLARITONE_CAMERA_LED_GPIO_CLK_ENABLE() __HAL_RCC_GPIOG_CLK_ENABLE()
#define CLARITONE_CAMERA_LED_PORT              GPIOG
#define CLARITONE_CAMERA_LED_PIN               GPIO_PIN_3

#define CLARITONE_CAMERA_SELECTED_SENSOR      CMW_VD55G1_Sensor

#endif /* CLARITONE_CUSTOM_BOARD_H */
