################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_blazeface.c \
C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_centernet.c \
C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_ssd.c \
C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_st_yolox.c \
C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_yolo_d.c \
C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_yolov2.c \
C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_yolov4.c \
C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_yolov5.c \
C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_yolov8.c \
C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/vision_models_pp.c \
C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/vision_models_pp_maxi_if32.c \
C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/vision_models_pp_maxi_is8.c \
C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/vision_models_pp_maxi_iu8.c 

OBJS += \
./stm32-vision-models-postprocessing/od_pp_blazeface.o \
./stm32-vision-models-postprocessing/od_pp_centernet.o \
./stm32-vision-models-postprocessing/od_pp_ssd.o \
./stm32-vision-models-postprocessing/od_pp_st_yolox.o \
./stm32-vision-models-postprocessing/od_pp_yolo_d.o \
./stm32-vision-models-postprocessing/od_pp_yolov2.o \
./stm32-vision-models-postprocessing/od_pp_yolov4.o \
./stm32-vision-models-postprocessing/od_pp_yolov5.o \
./stm32-vision-models-postprocessing/od_pp_yolov8.o \
./stm32-vision-models-postprocessing/vision_models_pp.o \
./stm32-vision-models-postprocessing/vision_models_pp_maxi_if32.o \
./stm32-vision-models-postprocessing/vision_models_pp_maxi_is8.o \
./stm32-vision-models-postprocessing/vision_models_pp_maxi_iu8.o 

C_DEPS += \
./stm32-vision-models-postprocessing/od_pp_blazeface.d \
./stm32-vision-models-postprocessing/od_pp_centernet.d \
./stm32-vision-models-postprocessing/od_pp_ssd.d \
./stm32-vision-models-postprocessing/od_pp_st_yolox.d \
./stm32-vision-models-postprocessing/od_pp_yolo_d.d \
./stm32-vision-models-postprocessing/od_pp_yolov2.d \
./stm32-vision-models-postprocessing/od_pp_yolov4.d \
./stm32-vision-models-postprocessing/od_pp_yolov5.d \
./stm32-vision-models-postprocessing/od_pp_yolov8.d \
./stm32-vision-models-postprocessing/vision_models_pp.d \
./stm32-vision-models-postprocessing/vision_models_pp_maxi_if32.d \
./stm32-vision-models-postprocessing/vision_models_pp_maxi_is8.d \
./stm32-vision-models-postprocessing/vision_models_pp_maxi_iu8.d 


# Each subdirectory must supply rules for building sources it contributes
stm32-vision-models-postprocessing/od_pp_blazeface.o: C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_blazeface.c stm32-vision-models-postprocessing/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/CLARITONE-CUSTOM-PCB -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"stm32-vision-models-postprocessing/od_pp_blazeface.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32-vision-models-postprocessing/od_pp_centernet.o: C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_centernet.c stm32-vision-models-postprocessing/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/CLARITONE-CUSTOM-PCB -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"stm32-vision-models-postprocessing/od_pp_centernet.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32-vision-models-postprocessing/od_pp_ssd.o: C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_ssd.c stm32-vision-models-postprocessing/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/CLARITONE-CUSTOM-PCB -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"stm32-vision-models-postprocessing/od_pp_ssd.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32-vision-models-postprocessing/od_pp_st_yolox.o: C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_st_yolox.c stm32-vision-models-postprocessing/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/CLARITONE-CUSTOM-PCB -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"stm32-vision-models-postprocessing/od_pp_st_yolox.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32-vision-models-postprocessing/od_pp_yolo_d.o: C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_yolo_d.c stm32-vision-models-postprocessing/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/CLARITONE-CUSTOM-PCB -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"stm32-vision-models-postprocessing/od_pp_yolo_d.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32-vision-models-postprocessing/od_pp_yolov2.o: C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_yolov2.c stm32-vision-models-postprocessing/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/CLARITONE-CUSTOM-PCB -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"stm32-vision-models-postprocessing/od_pp_yolov2.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32-vision-models-postprocessing/od_pp_yolov4.o: C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_yolov4.c stm32-vision-models-postprocessing/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/CLARITONE-CUSTOM-PCB -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"stm32-vision-models-postprocessing/od_pp_yolov4.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32-vision-models-postprocessing/od_pp_yolov5.o: C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_yolov5.c stm32-vision-models-postprocessing/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/CLARITONE-CUSTOM-PCB -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"stm32-vision-models-postprocessing/od_pp_yolov5.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32-vision-models-postprocessing/od_pp_yolov8.o: C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/od_pp_yolov8.c stm32-vision-models-postprocessing/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/CLARITONE-CUSTOM-PCB -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"stm32-vision-models-postprocessing/od_pp_yolov8.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32-vision-models-postprocessing/vision_models_pp.o: C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/vision_models_pp.c stm32-vision-models-postprocessing/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/CLARITONE-CUSTOM-PCB -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"stm32-vision-models-postprocessing/vision_models_pp.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32-vision-models-postprocessing/vision_models_pp_maxi_if32.o: C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/vision_models_pp_maxi_if32.c stm32-vision-models-postprocessing/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/CLARITONE-CUSTOM-PCB -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"stm32-vision-models-postprocessing/vision_models_pp_maxi_if32.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32-vision-models-postprocessing/vision_models_pp_maxi_is8.o: C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/vision_models_pp_maxi_is8.c stm32-vision-models-postprocessing/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/CLARITONE-CUSTOM-PCB -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"stm32-vision-models-postprocessing/vision_models_pp_maxi_is8.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
stm32-vision-models-postprocessing/vision_models_pp_maxi_iu8.o: C:/Users/Thepr/Blindsight-Claritone-Senior-Design/Object\ Detection/STM32N6/Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Src/vision_models_pp_maxi_iu8.c stm32-vision-models-postprocessing/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/stm32-vision-models-postprocessing/lib_vision_models_pp/Inc -I../../../../Middlewares/stedgeai-lib/Npu/ll_aton -I../../../../Middlewares/stedgeai-lib/Npu/Devices/STM32N6xx -I../../../../Model/CLARITONE-CUSTOM-PCB -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/stm32-mw-camera/ISP_Library/isp/Inc -I../../../../Middlewares/stedgeai-lib/Inc -I../../../../Middlewares/stm32-mw-camera -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/stm32-mw-camera/sensors -I../../../../Middlewares/stm32-mw-camera/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"stm32-vision-models-postprocessing/vision_models_pp_maxi_iu8.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-stm32-2d-vision-2d-models-2d-postprocessing

clean-stm32-2d-vision-2d-models-2d-postprocessing:
	-$(RM) ./stm32-vision-models-postprocessing/od_pp_blazeface.cyclo ./stm32-vision-models-postprocessing/od_pp_blazeface.d ./stm32-vision-models-postprocessing/od_pp_blazeface.o ./stm32-vision-models-postprocessing/od_pp_blazeface.su ./stm32-vision-models-postprocessing/od_pp_centernet.cyclo ./stm32-vision-models-postprocessing/od_pp_centernet.d ./stm32-vision-models-postprocessing/od_pp_centernet.o ./stm32-vision-models-postprocessing/od_pp_centernet.su ./stm32-vision-models-postprocessing/od_pp_ssd.cyclo ./stm32-vision-models-postprocessing/od_pp_ssd.d ./stm32-vision-models-postprocessing/od_pp_ssd.o ./stm32-vision-models-postprocessing/od_pp_ssd.su ./stm32-vision-models-postprocessing/od_pp_st_yolox.cyclo ./stm32-vision-models-postprocessing/od_pp_st_yolox.d ./stm32-vision-models-postprocessing/od_pp_st_yolox.o ./stm32-vision-models-postprocessing/od_pp_st_yolox.su ./stm32-vision-models-postprocessing/od_pp_yolo_d.cyclo ./stm32-vision-models-postprocessing/od_pp_yolo_d.d ./stm32-vision-models-postprocessing/od_pp_yolo_d.o ./stm32-vision-models-postprocessing/od_pp_yolo_d.su ./stm32-vision-models-postprocessing/od_pp_yolov2.cyclo ./stm32-vision-models-postprocessing/od_pp_yolov2.d ./stm32-vision-models-postprocessing/od_pp_yolov2.o ./stm32-vision-models-postprocessing/od_pp_yolov2.su ./stm32-vision-models-postprocessing/od_pp_yolov4.cyclo ./stm32-vision-models-postprocessing/od_pp_yolov4.d ./stm32-vision-models-postprocessing/od_pp_yolov4.o ./stm32-vision-models-postprocessing/od_pp_yolov4.su ./stm32-vision-models-postprocessing/od_pp_yolov5.cyclo ./stm32-vision-models-postprocessing/od_pp_yolov5.d ./stm32-vision-models-postprocessing/od_pp_yolov5.o ./stm32-vision-models-postprocessing/od_pp_yolov5.su ./stm32-vision-models-postprocessing/od_pp_yolov8.cyclo ./stm32-vision-models-postprocessing/od_pp_yolov8.d ./stm32-vision-models-postprocessing/od_pp_yolov8.o ./stm32-vision-models-postprocessing/od_pp_yolov8.su ./stm32-vision-models-postprocessing/vision_models_pp.cyclo ./stm32-vision-models-postprocessing/vision_models_pp.d ./stm32-vision-models-postprocessing/vision_models_pp.o ./stm32-vision-models-postprocessing/vision_models_pp.su ./stm32-vision-models-postprocessing/vision_models_pp_maxi_if32.cyclo ./stm32-vision-models-postprocessing/vision_models_pp_maxi_if32.d ./stm32-vision-models-postprocessing/vision_models_pp_maxi_if32.o ./stm32-vision-models-postprocessing/vision_models_pp_maxi_if32.su ./stm32-vision-models-postprocessing/vision_models_pp_maxi_is8.cyclo ./stm32-vision-models-postprocessing/vision_models_pp_maxi_is8.d ./stm32-vision-models-postprocessing/vision_models_pp_maxi_is8.o ./stm32-vision-models-postprocessing/vision_models_pp_maxi_is8.su ./stm32-vision-models-postprocessing/vision_models_pp_maxi_iu8.cyclo ./stm32-vision-models-postprocessing/vision_models_pp_maxi_iu8.d ./stm32-vision-models-postprocessing/vision_models_pp_maxi_iu8.o ./stm32-vision-models-postprocessing/vision_models_pp_maxi_iu8.su

.PHONY: clean-stm32-2d-vision-2d-models-2d-postprocessing

